package ModPerl::FunctionTable;

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# ! WARNING: generated by ModPerl::ParseSource/0.01
# !          Wed Sep 12 21:41:47 2001
# !          do NOT edit, any changes will be lost !
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

$ModPerl::FunctionTable = [
  {
    'return_type' => 'int',
    'name' => 'modperl_access_handler',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'char *',
    'name' => 'modperl_apr_strerror',
    'args' => [
      {
        'type' => 'apr_status_t',
        'name' => 'rv'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_authen_handler',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_authz_handler',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_brigade_dump',
    'args' => [
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'bb'
      },
      {
        'type' => 'FILE *',
        'name' => 'fp'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_bucket_read',
    'args' => [
      {
        'type' => 'apr_bucket *',
        'name' => 'bucket'
      },
      {
        'type' => 'const char **',
        'name' => 'str'
      },
      {
        'type' => 'apr_size_t *',
        'name' => 'len'
      },
      {
        'type' => 'apr_read_type_e',
        'name' => 'block'
      }
    ]
  },
  {
    'return_type' => 'apr_bucket *',
    'name' => 'modperl_bucket_sv_create',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      },
      {
        'type' => 'int',
        'name' => 'offset'
      },
      {
        'type' => 'int',
        'name' => 'len'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_callback',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'modperl_handler_t *',
        'name' => 'handler'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'AV *',
        'name' => 'args'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_callback_connection',
    'args' => [
      {
        'type' => 'int',
        'name' => 'idx'
      },
      {
        'type' => 'conn_rec *',
        'name' => 'c'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_callback_files',
    'args' => [
      {
        'type' => 'int',
        'name' => 'idx'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'pconf'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'plog'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'ptemp'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_callback_per_dir',
    'args' => [
      {
        'type' => 'int',
        'name' => 'idx'
      },
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_callback_per_srv',
    'args' => [
      {
        'type' => 'int',
        'name' => 'idx'
      },
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_callback_process',
    'args' => [
      {
        'type' => 'int',
        'name' => 'idx'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_callback_run_handlers',
    'args' => [
      {
        'type' => 'int',
        'name' => 'idx'
      },
      {
        'type' => 'int',
        'name' => 'type'
      },
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'conn_rec *',
        'name' => 'c'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'pconf'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'plog'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'ptemp'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_cgi_header_parse',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'char *',
        'name' => 'buffer'
      },
      {
        'type' => 'const char **',
        'name' => 'bodytext'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_child_init_handler',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'modperl_cleanup_data_t *',
    'name' => 'modperl_cleanup_data_new',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'void *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_access_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_authen_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_authz_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_child_init_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_fixup_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_header_parser_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_input_filter_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_interp_max',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_interp_max_requests',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_interp_max_spare',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_interp_min_spare',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_interp_scope',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_interp_start',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_log_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_modules',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_open_logs_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_options',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_output_filter_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_post_config_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_post_read_request_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_pre_connection_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_process_connection_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'char *',
    'name' => 'modperl_cmd_push_handlers',
    'args' => [
      {
        'type' => 'MpAV **',
        'name' => 'handlers'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_requires',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_response_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_switches',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_trace',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_trans_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_cmd_type_handlers',
    'args' => [
      {
        'type' => 'cmd_parms *',
        'name' => 'parms'
      },
      {
        'type' => 'void *',
        'name' => 'dummy'
      },
      {
        'type' => 'const char *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_config_apply_PerlModule',
    'args' => [
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'modperl_config_srv_t *',
        'name' => 'scfg'
      },
      {
        'type' => 'PerlInterpreter *',
        'name' => 'perl'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_config_apply_PerlRequire',
    'args' => [
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'modperl_config_srv_t *',
        'name' => 'scfg'
      },
      {
        'type' => 'PerlInterpreter *',
        'name' => 'perl'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'void *',
    'name' => 'modperl_config_dir_create',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'char *',
        'name' => 'dir'
      }
    ]
  },
  {
    'return_type' => 'void *',
    'name' => 'modperl_config_dir_merge',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'void *',
        'name' => 'basev'
      },
      {
        'type' => 'void *',
        'name' => 'addv'
      }
    ]
  },
  {
    'return_type' => 'modperl_config_dir_t *',
    'name' => 'modperl_config_dir_new',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'modperl_config_req_t *',
    'name' => 'modperl_config_req_new',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'char **',
    'name' => 'modperl_config_srv_argv_init',
    'args' => [
      {
        'type' => 'modperl_config_srv_t *',
        'name' => 'scfg'
      },
      {
        'type' => 'int *',
        'name' => 'argc'
      }
    ]
  },
  {
    'return_type' => 'void *',
    'name' => 'modperl_config_srv_create',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'void *',
    'name' => 'modperl_config_srv_merge',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'void *',
        'name' => 'basev'
      },
      {
        'type' => 'void *',
        'name' => 'addv'
      }
    ]
  },
  {
    'return_type' => 'modperl_config_srv_t *',
    'name' => 'modperl_config_srv_new',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_env_request_tie',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_env_request_untie',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_errsv',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'int',
        'name' => 'status'
      },
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'U32 *',
    'name' => 'modperl_filter_attributes',
    'args' => [
      {
        'type' => 'SV *',
        'name' => 'package'
      },
      {
        'type' => 'SV *',
        'name' => 'cvrv'
      }
    ]
  },
  {
    'return_type' => 'modperl_filter_t *',
    'name' => 'modperl_filter_mg_get',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'obj'
      }
    ]
  },
  {
    'return_type' => 'modperl_filter_t *',
    'name' => 'modperl_filter_new',
    'args' => [
      {
        'type' => 'ap_filter_t *',
        'name' => 'f'
      },
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'bb'
      },
      {
        'type' => 'modperl_filter_mode_e',
        'name' => 'mode'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_fixup_handler',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'U32',
    'name' => 'modperl_flags_lookup_dir',
    'args' => [
      {
        'type' => 'const char *',
        'name' => 'str'
      }
    ]
  },
  {
    'return_type' => 'U32',
    'name' => 'modperl_flags_lookup_srv',
    'args' => [
      {
        'type' => 'const char *',
        'name' => 'str'
      }
    ]
  },
  {
    'return_type' => 'void *',
    'name' => 'modperl_global_get',
    'args' => [
      {
        'type' => 'modperl_global_t *',
        'name' => 'global'
      }
    ]
  },
  {
    'return_type' => 'apr_pool_t *',
    'name' => 'modperl_global_get_pconf',
    'args' => []
  },
  {
    'return_type' => 'server_rec *',
    'name' => 'modperl_global_get_server_rec',
    'args' => []
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_global_get_threaded_mpm',
    'args' => []
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_init',
    'args' => [
      {
        'type' => 'modperl_global_t *',
        'name' => 'global'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'void *',
        'name' => 'data'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_init_pconf',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'pconf'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_init_server_rec',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'server_rec * server_rec',
        'name' => 'arg1'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_init_threaded_mpm',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'int',
        'name' => 'threaded_mpm'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_lock',
    'args' => [
      {
        'type' => 'modperl_global_t *',
        'name' => 'global'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_lock_pconf',
    'args' => []
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_lock_server_rec',
    'args' => []
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_lock_threaded_mpm',
    'args' => []
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_request_cfg_set',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_request_obj_set',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'svr'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_request_set',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_set',
    'args' => [
      {
        'type' => 'modperl_global_t *',
        'name' => 'global'
      },
      {
        'type' => 'void *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_set_pconf',
    'args' => [
      {
        'type' => 'void *',
        'name' => 'arg0'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_set_server_rec',
    'args' => [
      {
        'type' => 'void *',
        'name' => 'arg0'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_set_threaded_mpm',
    'args' => [
      {
        'type' => 'void *',
        'name' => 'arg0'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_unlock',
    'args' => [
      {
        'type' => 'modperl_global_t *',
        'name' => 'global'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_unlock_pconf',
    'args' => []
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_unlock_server_rec',
    'args' => []
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_global_unlock_threaded_mpm',
    'args' => []
  },
  {
    'return_type' => 'MpAV *',
    'name' => 'modperl_handler_array_merge',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'MpAV *',
        'name' => 'base_a'
      },
      {
        'type' => 'MpAV *',
        'name' => 'add_a'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_handler_desc_connection',
    'args' => [
      {
        'type' => 'int',
        'name' => 'idx'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_handler_desc_files',
    'args' => [
      {
        'type' => 'int',
        'name' => 'idx'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_handler_desc_per_dir',
    'args' => [
      {
        'type' => 'int',
        'name' => 'idx'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_handler_desc_per_srv',
    'args' => [
      {
        'type' => 'int',
        'name' => 'idx'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_handler_desc_process',
    'args' => [
      {
        'type' => 'int',
        'name' => 'idx'
      }
    ]
  },
  {
    'return_type' => 'modperl_handler_t *',
    'name' => 'modperl_handler_dup',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'modperl_handler_t *',
        'name' => 'h'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_handler_equal',
    'args' => [
      {
        'type' => 'modperl_handler_t *',
        'name' => 'h1'
      },
      {
        'type' => 'modperl_handler_t *',
        'name' => 'h2'
      }
    ]
  },
  {
    'return_type' => 'MpAV **',
    'name' => 'modperl_handler_get_handlers',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'conn_rec *',
        'name' => 'c'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      },
      {
        'type' => 'modperl_handler_action_e',
        'name' => 'action'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_handler_lookup',
    'args' => [
      {
        'type' => 'const char *',
        'name' => 'name'
      },
      {
        'type' => 'int *',
        'name' => 'type'
      }
    ]
  },
  {
    'return_type' => 'MpAV **',
    'name' => 'modperl_handler_lookup_handlers',
    'args' => [
      {
        'type' => 'modperl_config_dir_t *',
        'name' => 'dcfg'
      },
      {
        'type' => 'modperl_config_srv_t *',
        'name' => 'scfg'
      },
      {
        'type' => 'modperl_config_req_t *',
        'name' => 'rcfg'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'int',
        'name' => 'type'
      },
      {
        'type' => 'int',
        'name' => 'idx'
      },
      {
        'type' => 'modperl_handler_action_e',
        'name' => 'action'
      },
      {
        'type' => 'const char **',
        'name' => 'desc'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_handler_make_args',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'AV **',
        'name' => 'avp'
      },
      {
        'type' => '...',
        'name' => 'arg2'
      }
    ]
  },
  {
    'return_type' => 'modperl_handler_t *',
    'name' => 'modperl_handler_new',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_handler_perl_add_handlers',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'conn_rec *',
        'name' => 'c'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      },
      {
        'type' => 'modperl_handler_action_e',
        'name' => 'action'
      }
    ]
  },
  {
    'return_type' => 'SV *',
    'name' => 'modperl_handler_perl_get_handlers',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'MpAV **',
        'name' => 'handp'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_handler_push_handlers',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'MpAV *',
        'name' => 'handlers'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_handler_resolve',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'modperl_handler_t **',
        'name' => 'handp'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_header_parser_handler',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_hook_init',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'pconf'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'plog'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'ptemp'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_init',
    'args' => [
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_input_filter_handler',
    'args' => [
      {
        'type' => 'ap_filter_t *',
        'name' => 'f'
      },
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'bb'
      },
      {
        'type' => 'ap_input_mode_t',
        'name' => 'mode'
      },
      {
        'type' => 'apr_off_t *',
        'name' => 'readbytes'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_input_filter_register_connection',
    'args' => [
      {
        'type' => 'conn_rec *',
        'name' => 'c'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_input_filter_register_request',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_interp_cleanup',
    'args' => [
      {
        'type' => 'void *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_interp_clone_init',
    'args' => [
      {
        'type' => 'modperl_interp_t *',
        'name' => 'interp'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_interp_destroy',
    'args' => [
      {
        'type' => 'modperl_interp_t *',
        'name' => 'interp'
      }
    ]
  },
  {
    'return_type' => 'modperl_interp_t *',
    'name' => 'modperl_interp_get',
    'args' => [
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_interp_init',
    'args' => [
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'PerlInterpreter *',
        'name' => 'perl'
      }
    ]
  },
  {
    'return_type' => 'modperl_interp_t *',
    'name' => 'modperl_interp_new',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'modperl_interp_pool_t *',
        'name' => 'mip'
      },
      {
        'type' => 'PerlInterpreter *',
        'name' => 'perl'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_interp_pool_add',
    'args' => [
      {
        'type' => 'modperl_interp_pool_t *',
        'name' => 'mip'
      },
      {
        'type' => 'modperl_interp_t *',
        'name' => 'interp'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_interp_pool_destroy',
    'args' => [
      {
        'type' => 'void *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_interp_pool_remove',
    'args' => [
      {
        'type' => 'modperl_interp_pool_t *',
        'name' => 'mip'
      },
      {
        'type' => 'modperl_interp_t *',
        'name' => 'interp'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_interp_scope_desc',
    'args' => [
      {
        'type' => 'modperl_interp_scope_e',
        'name' => 'scope'
      }
    ]
  },
  {
    'return_type' => 'modperl_interp_t *',
    'name' => 'modperl_interp_select',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'conn_rec *',
        'name' => 'c'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_interp_unselect',
    'args' => [
      {
        'type' => 'void *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_io_handle_tie',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'GV *',
        'name' => 'handle'
      },
      {
        'type' => 'char *',
        'name' => 'classname'
      },
      {
        'type' => 'void *',
        'name' => 'ptr'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_io_handle_tied',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'GV *',
        'name' => 'handle'
      },
      {
        'type' => 'char *',
        'name' => 'classname'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_io_handle_untie',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'GV *',
        'name' => 'handle'
      }
    ]
  },
  {
    'return_type' => 'GV *',
    'name' => 'modperl_io_tie_stdin',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'GV *',
    'name' => 'modperl_io_tie_stdout',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'modperl_list_t *',
    'name' => 'modperl_list_append',
    'args' => [
      {
        'type' => 'modperl_list_t *',
        'name' => 'list'
      },
      {
        'type' => 'modperl_list_t *',
        'name' => 'new_list'
      }
    ]
  },
  {
    'return_type' => 'modperl_list_t *',
    'name' => 'modperl_list_first',
    'args' => [
      {
        'type' => 'modperl_list_t *',
        'name' => 'list'
      }
    ]
  },
  {
    'return_type' => 'modperl_list_t *',
    'name' => 'modperl_list_last',
    'args' => [
      {
        'type' => 'modperl_list_t *',
        'name' => 'list'
      }
    ]
  },
  {
    'return_type' => 'modperl_list_t *',
    'name' => 'modperl_list_new',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'modperl_list_t *',
    'name' => 'modperl_list_prepend',
    'args' => [
      {
        'type' => 'modperl_list_t *',
        'name' => 'list'
      },
      {
        'type' => 'modperl_list_t *',
        'name' => 'new_list'
      }
    ]
  },
  {
    'return_type' => 'modperl_list_t *',
    'name' => 'modperl_list_remove',
    'args' => [
      {
        'type' => 'modperl_list_t *',
        'name' => 'list'
      },
      {
        'type' => 'modperl_list_t *',
        'name' => 'rlist'
      }
    ]
  },
  {
    'return_type' => 'modperl_list_t *',
    'name' => 'modperl_list_remove_data',
    'args' => [
      {
        'type' => 'modperl_list_t *',
        'name' => 'list'
      },
      {
        'type' => 'void *',
        'name' => 'data'
      },
      {
        'type' => 'modperl_list_t **',
        'name' => 'listp'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_log_handler',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_mgv_append',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'modperl_mgv_t *',
        'name' => 'symbol'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      }
    ]
  },
  {
    'return_type' => 'char *',
    'name' => 'modperl_mgv_as_string',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'modperl_mgv_t *',
        'name' => 'symbol'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'int',
        'name' => 'package'
      }
    ]
  },
  {
    'return_type' => 'modperl_mgv_t *',
    'name' => 'modperl_mgv_compile',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_mgv_equal',
    'args' => [
      {
        'type' => 'modperl_mgv_t *',
        'name' => 'mgv1'
      },
      {
        'type' => 'modperl_mgv_t *',
        'name' => 'mgv2'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_mgv_hash_handlers',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'GV *',
    'name' => 'modperl_mgv_lookup',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'modperl_mgv_t *',
        'name' => 'symbol'
      }
    ]
  },
  {
    'return_type' => 'GV *',
    'name' => 'modperl_mgv_lookup_autoload',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'modperl_mgv_t *',
        'name' => 'symbol'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'char *',
    'name' => 'modperl_mgv_name_from_sv',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      }
    ]
  },
  {
    'return_type' => 'modperl_mgv_t *',
    'name' => 'modperl_mgv_new',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_mgv_require_module',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'modperl_mgv_t *',
        'name' => 'symbol'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_mgv_resolve',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'modperl_handler_t *',
        'name' => 'handler'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      }
    ]
  },
  {
    'return_type' => 'SV *',
    'name' => 'modperl_newSVsv_obj',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'stashsv'
      },
      {
        'type' => 'SV *',
        'name' => 'obj'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_open_logs_handler',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'pconf'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'plog'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'ptemp'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'modperl_options_t *',
    'name' => 'modperl_options_merge',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'modperl_options_t *',
        'name' => 'base'
      },
      {
        'type' => 'modperl_options_t *new',
        'name' => 'arg2'
      }
    ]
  },
  {
    'return_type' => 'modperl_options_t *',
    'name' => 'modperl_options_new',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'int',
        'name' => 'type'
      }
    ]
  },
  {
    'return_type' => 'const char *',
    'name' => 'modperl_options_set',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'modperl_options_t *',
        'name' => 'o'
      },
      {
        'type' => 'const char *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_output_filter_flush',
    'args' => [
      {
        'type' => 'modperl_filter_t *',
        'name' => 'filter'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_output_filter_handler',
    'args' => [
      {
        'type' => 'ap_filter_t *',
        'name' => 'f'
      },
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'bb'
      }
    ]
  },
  {
    'return_type' => 'apr_ssize_t',
    'name' => 'modperl_output_filter_read',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'modperl_filter_t *',
        'name' => 'filter'
      },
      {
        'type' => 'SV *',
        'name' => 'buffer'
      },
      {
        'type' => 'apr_ssize_t',
        'name' => 'wanted'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_output_filter_register_connection',
    'args' => [
      {
        'type' => 'conn_rec *',
        'name' => 'c'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_output_filter_register_request',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_output_filter_write',
    'args' => [
      {
        'type' => 'modperl_filter_t *',
        'name' => 'filter'
      },
      {
        'type' => 'const char *',
        'name' => 'buf'
      },
      {
        'type' => 'apr_ssize_t *',
        'name' => 'len'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_post_config_handler',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'pconf'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'plog'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'ptemp'
      },
      {
        'type' => 'server_rec *',
        'name' => 's'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_post_read_request_handler',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_pre_config_handler',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'plog'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'ptemp'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_pre_connection_handler',
    'args' => [
      {
        'type' => 'conn_rec *',
        'name' => 'c'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_process_connection_handler',
    'args' => [
      {
        'type' => 'conn_rec *',
        'name' => 'c'
      }
    ]
  },
  {
    'return_type' => 'SV *',
    'name' => 'modperl_ptr2obj',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'char *',
        'name' => 'classname'
      },
      {
        'type' => 'void *',
        'name' => 'ptr'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_register_handler_hooks',
    'args' => []
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_register_hooks',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_require_file',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'const char *',
        'name' => 'pv'
      },
      {
        'type' => 'int',
        'name' => 'logfailure'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_require_module',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'const char *',
        'name' => 'pv'
      },
      {
        'type' => 'int',
        'name' => 'logfailure'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_response_finish',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_response_handler',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_response_handler_cgi',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_response_init',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_run_filter',
    'args' => [
      {
        'type' => 'modperl_filter_t *',
        'name' => 'filter'
      },
      {
        'type' => 'ap_input_mode_t',
        'name' => 'mode'
      },
      {
        'type' => 'apr_off_t *',
        'name' => 'readbytes'
      }
    ]
  },
  {
    'return_type' => 'char *',
    'name' => 'modperl_server_desc',
    'args' => [
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'PerlInterpreter *',
    'name' => 'modperl_startup',
    'args' => [
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'apr_pool_t *',
    'name' => 'modperl_sv2pool',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'obj'
      }
    ]
  },
  {
    'return_type' => 'request_rec *',
    'name' => 'modperl_sv2request_rec',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      }
    ]
  },
  {
    'return_type' => 'server_rec *',
    'name' => 'modperl_sv2server_rec',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_tipool_add',
    'args' => [
      {
        'type' => 'modperl_tipool_t *',
        'name' => 'tipool'
      },
      {
        'type' => 'void *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_tipool_destroy',
    'args' => [
      {
        'type' => 'modperl_tipool_t *',
        'name' => 'tipool'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_tipool_init',
    'args' => [
      {
        'type' => 'modperl_tipool_t *',
        'name' => 'tipool'
      }
    ]
  },
  {
    'return_type' => 'modperl_tipool_t *',
    'name' => 'modperl_tipool_new',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'modperl_tipool_config_t *',
        'name' => 'cfg'
      },
      {
        'type' => 'modperl_tipool_vtbl_t *',
        'name' => 'func'
      },
      {
        'type' => 'void *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'modperl_list_t *',
    'name' => 'modperl_tipool_pop',
    'args' => [
      {
        'type' => 'modperl_tipool_t *',
        'name' => 'tipool'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_tipool_putback',
    'args' => [
      {
        'type' => 'modperl_tipool_t *',
        'name' => 'tipool'
      },
      {
        'type' => 'modperl_list_t *',
        'name' => 'listp'
      },
      {
        'type' => 'int',
        'name' => 'num_requests'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_tipool_putback_data',
    'args' => [
      {
        'type' => 'modperl_tipool_t *',
        'name' => 'tipool'
      },
      {
        'type' => 'void *',
        'name' => 'data'
      },
      {
        'type' => 'int',
        'name' => 'num_requests'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_tipool_remove',
    'args' => [
      {
        'type' => 'modperl_tipool_t *',
        'name' => 'tipool'
      },
      {
        'type' => 'modperl_list_t *',
        'name' => 'listp'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_tls_create',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'modperl_tls_t **',
        'name' => 'key'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_tls_create_request_rec',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_tls_get',
    'args' => [
      {
        'type' => 'modperl_tls_t *',
        'name' => 'key'
      },
      {
        'type' => 'void **',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_tls_get_request_rec',
    'args' => [
      {
        'type' => 'request_rec * *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_tls_reset_cleanup',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'modperl_tls_t *',
        'name' => 'key'
      },
      {
        'type' => 'void *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_tls_reset_cleanup_request_rec',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'request_rec *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_tls_set',
    'args' => [
      {
        'type' => 'modperl_tls_t *',
        'name' => 'key'
      },
      {
        'type' => 'void *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_tls_set_request_rec',
    'args' => [
      {
        'type' => 'void *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_trace',
    'args' => [
      {
        'type' => 'char *',
        'name' => 'func'
      },
      {
        'type' => 'const char *',
        'name' => 'fmt'
      },
      {
        'type' => '...',
        'name' => 'arg2'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_trace_level_set',
    'args' => [
      {
        'type' => 'const char *',
        'name' => 'level'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_trans_handler',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'modperl_type_handler',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'modperl_uri_t *',
    'name' => 'modperl_uri_new',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_wbucket_flush',
    'args' => [
      {
        'type' => 'modperl_wbucket_t *',
        'name' => 'b'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_wbucket_pass',
    'args' => [
      {
        'type' => 'modperl_wbucket_t *',
        'name' => 'b'
      },
      {
        'type' => 'const char *',
        'name' => 'buf'
      },
      {
        'type' => 'apr_ssize_t',
        'name' => 'len'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'modperl_wbucket_write',
    'args' => [
      {
        'type' => 'modperl_wbucket_t *',
        'name' => 'b'
      },
      {
        'type' => 'const char *',
        'name' => 'buf'
      },
      {
        'type' => 'apr_ssize_t *',
        'name' => 'wlen'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_xs_dl_handles_clear',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'modperl_xs_dl_handles_close',
    'args' => [
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'apr_array_header_t *',
        'name' => 'handles'
      }
    ]
  },
  {
    'return_type' => 'apr_array_header_t *',
    'name' => 'modperl_xs_dl_handles_get',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'request_rec *',
    'name' => 'modperl_xs_sv2request_rec',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      },
      {
        'type' => 'char *',
        'name' => 'classname'
      },
      {
        'type' => 'CV *',
        'name' => 'cv'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_APR__Brigade_concat',
    'args' => [
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'a'
      },
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'b'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'mpxs_APR__Brigade_empty',
    'args' => [
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'brigade'
      }
    ]
  },
  {
    'return_type' => 'apr_bucket *',
    'name' => 'mpxs_APR__Brigade_first',
    'args' => [
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'brigade'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_APR__Brigade_insert_head',
    'args' => [
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'brigade'
      },
      {
        'type' => 'apr_bucket *',
        'name' => 'bucket'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_APR__Brigade_insert_tail',
    'args' => [
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'brigade'
      },
      {
        'type' => 'apr_bucket *',
        'name' => 'bucket'
      }
    ]
  },
  {
    'return_type' => 'apr_bucket *',
    'name' => 'mpxs_APR__Brigade_last',
    'args' => [
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'brigade'
      }
    ]
  },
  {
    'return_type' => 'apr_bucket *',
    'name' => 'mpxs_APR__Brigade_next',
    'args' => [
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'brigade'
      },
      {
        'type' => 'apr_bucket *',
        'name' => 'bucket'
      }
    ]
  },
  {
    'return_type' => 'apr_bucket *',
    'name' => 'mpxs_APR__Brigade_prev',
    'args' => [
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'brigade'
      },
      {
        'type' => 'apr_bucket *',
        'name' => 'bucket'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_APR__Bucket_insert_after',
    'args' => [
      {
        'type' => 'apr_bucket *',
        'name' => 'a'
      },
      {
        'type' => 'apr_bucket *',
        'name' => 'b'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_APR__Bucket_insert_before',
    'args' => [
      {
        'type' => 'apr_bucket *',
        'name' => 'a'
      },
      {
        'type' => 'apr_bucket *',
        'name' => 'b'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'mpxs_APR__Bucket_is_eos',
    'args' => [
      {
        'type' => 'apr_bucket *',
        'name' => 'bucket'
      }
    ]
  },
  {
    'return_type' => 'apr_bucket *',
    'name' => 'mpxs_APR__Bucket_new',
    'args' => [
      {
        'type' => 'SV *',
        'name' => 'classname'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      },
      {
        'type' => 'int',
        'name' => 'offset'
      },
      {
        'type' => 'int',
        'name' => 'len'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_APR__Bucket_remove',
    'args' => [
      {
        'type' => 'apr_bucket *',
        'name' => 'bucket'
      }
    ]
  },
  {
    'return_type' => 'char *',
    'name' => 'mpxs_APR__URI_port',
    'args' => [
      {
        'type' => 'apr_uri_t *',
        'name' => 'uri'
      },
      {
        'type' => 'SV *',
        'name' => 'portsv'
      }
    ]
  },
  {
    'return_type' => 'apr_size_t',
    'name' => 'mpxs_Apache__Filter_print',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'I32',
        'name' => 'items'
      },
      {
        'type' => 'SV **',
        'name' => 'mark'
      },
      {
        'type' => 'SV **',
        'name' => 'sp'
      }
    ]
  },
  {
    'return_type' => 'apr_size_t',
    'name' => 'mpxs_Apache__Filter_read',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'I32',
        'name' => 'items'
      },
      {
        'type' => 'SV **',
        'name' => 'mark'
      },
      {
        'type' => 'SV **',
        'name' => 'sp'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_Apache__Log_BOOT',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      }
    ]
  },
  {
    'return_type' => 'SV *',
    'name' => 'mpxs_Apache__Log_log',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      },
      {
        'type' => 'int',
        'name' => 'logtype'
      }
    ]
  },
  {
    'return_type' => 'SV *',
    'name' => 'mpxs_Apache__RequestRec_get_handlers',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'mpxs_Apache__RequestRec_location_merge',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'char *',
        'name' => 'location'
      }
    ]
  },
  {
    'return_type' => 'request_rec *',
    'name' => 'mpxs_Apache__RequestRec_new',
    'args' => [
      {
        'type' => 'SV *',
        'name' => 'classname'
      },
      {
        'type' => 'conn_rec *',
        'name' => 'c'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'base_pool'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'mpxs_Apache__RequestRec_no_cache',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'SV *',
        'name' => 'flag'
      }
    ]
  },
  {
    'return_type' => 'apr_uri_t *',
    'name' => 'mpxs_Apache__RequestRec_parsed_uri',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'mpxs_Apache__RequestRec_push_handlers',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      }
    ]
  },
  {
    'return_type' => 'long',
    'name' => 'mpxs_Apache__RequestRec_read',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'SV *',
        'name' => 'buffer'
      },
      {
        'type' => 'int',
        'name' => 'bufsiz'
      },
      {
        'type' => 'int',
        'name' => 'offset'
      }
    ]
  },
  {
    'return_type' => '',
    'name' => 'mpxs_Apache__RequestRec_send_http_header',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'const char *',
        'name' => 'type'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'mpxs_Apache__RequestRec_sendfile',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'const char *',
        'name' => 'filename'
      },
      {
        'type' => 'apr_off_t',
        'name' => 'offset'
      },
      {
        'type' => 'apr_size_t',
        'name' => 'len'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_Apache__RequestRec_set_basic_credentials',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'char *',
        'name' => 'username'
      },
      {
        'type' => 'char *',
        'name' => 'password'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'mpxs_Apache__RequestRec_set_handlers',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      }
    ]
  },
  {
    'return_type' => 'apr_ssize_t',
    'name' => 'mpxs_Apache__RequestRec_write',
    'args' => [
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'SV *',
        'name' => 'buffer'
      },
      {
        'type' => 'apr_ssize_t',
        'name' => 'bufsiz'
      },
      {
        'type' => 'int',
        'name' => 'offset'
      }
    ]
  },
  {
    'return_type' => 'SV *',
    'name' => 'mpxs_Apache__Server_get_handlers',
    'args' => [
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'mpxs_Apache__Server_push_handlers',
    'args' => [
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'mpxs_Apache__Server_set_handlers',
    'args' => [
      {
        'type' => 'server_rec *',
        'name' => 's'
      },
      {
        'type' => 'const char *',
        'name' => 'name'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      }
    ]
  },
  {
    'return_type' => 'request_rec *',
    'name' => 'mpxs_Apache_request',
    'args' => [
      {
        'type' => 'SV *',
        'name' => 'classname'
      },
      {
        'type' => 'SV *',
        'name' => 'svr'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_ap_allow_methods',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'I32',
        'name' => 'items'
      },
      {
        'type' => 'SV **',
        'name' => 'mark'
      },
      {
        'type' => 'SV **',
        'name' => 'sp'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'mpxs_ap_get_brigade',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'ap_filter_t *',
        'name' => 'filter'
      },
      {
        'type' => 'apr_bucket_brigade *',
        'name' => 'brigade'
      },
      {
        'type' => 'ap_input_mode_t',
        'name' => 'mode'
      },
      {
        'type' => 'SV *',
        'name' => 'svreadbytes'
      }
    ]
  },
  {
    'return_type' => 'long',
    'name' => 'mpxs_ap_get_client_block',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'request_rec *',
        'name' => 'r'
      },
      {
        'type' => 'SV *',
        'name' => 'buffer'
      },
      {
        'type' => 'int',
        'name' => 'bufsiz'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_ap_log_error',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'int',
        'name' => 'level'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      },
      {
        'type' => 'SV *',
        'name' => 'msg'
      }
    ]
  },
  {
    'return_type' => 'SV *',
    'name' => 'mpxs_ap_requires',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'request_rec *',
        'name' => 'r'
      }
    ]
  },
  {
    'return_type' => 'apr_size_t',
    'name' => 'mpxs_ap_rvputs',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'I32',
        'name' => 'items'
      },
      {
        'type' => 'SV **',
        'name' => 'mark'
      },
      {
        'type' => 'SV **',
        'name' => 'sp'
      }
    ]
  },
  {
    'return_type' => 'int',
    'name' => 'mpxs_ap_unescape_url',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'url'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_apr_base64_decode',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      },
      {
        'type' => 'SV *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_apr_base64_encode',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      },
      {
        'type' => 'SV *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'apr_bucket_brigade *',
    'name' => 'mpxs_apr_brigade_create',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'CLASS'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_apr_generate_random_bytes',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      },
      {
        'type' => 'SV *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'apr_ipsubnet_t *',
    'name' => 'mpxs_apr_ipsubnet_create',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'classname'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'const char *',
        'name' => 'ipstr'
      },
      {
        'type' => 'const char *',
        'name' => 'mask_or_numbits'
      }
    ]
  },
  {
    'return_type' => 'apr_lock_t *',
    'name' => 'mpxs_apr_lock_create',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'CLASS'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'apr_locktype_e',
        'name' => 'type'
      },
      {
        'type' => 'apr_lockscope_e',
        'name' => 'scope'
      },
      {
        'type' => 'const char *',
        'name' => 'fname'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_apr_pool_cleanup_register',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'apr_pool_t *',
        'name' => 'p'
      },
      {
        'type' => 'SV *',
        'name' => 'cv'
      },
      {
        'type' => 'SV *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'apr_pool_t *',
    'name' => 'mpxs_apr_pool_create',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'obj'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'mpxs_apr_recv',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'apr_socket_t *',
        'name' => 'socket'
      },
      {
        'type' => 'SV *',
        'name' => 'sv_buf'
      },
      {
        'type' => 'SV *',
        'name' => 'sv_len'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'mpxs_apr_send',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'apr_socket_t *',
        'name' => 'socket'
      },
      {
        'type' => 'SV *',
        'name' => 'sv_buf'
      },
      {
        'type' => 'SV *',
        'name' => 'sv_len'
      }
    ]
  },
  {
    'return_type' => 'void',
    'name' => 'mpxs_apr_strerror',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'sv'
      },
      {
        'type' => 'SV *',
        'name' => 'arg'
      }
    ]
  },
  {
    'return_type' => 'apr_uri_t *',
    'name' => 'mpxs_apr_uri_parse',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'classname'
      },
      {
        'type' => 'SV *',
        'name' => 'obj'
      },
      {
        'type' => 'const char *',
        'name' => 'uri_string'
      }
    ]
  },
  {
    'return_type' => 'char *',
    'name' => 'mpxs_apr_uri_unparse',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'apr_uri_t *',
        'name' => 'uptr'
      },
      {
        'type' => 'unsigned',
        'name' => 'flags'
      }
    ]
  },
  {
    'return_type' => 'apr_uuid_t *',
    'name' => 'mpxs_apr_uuid_get',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'CLASS'
      }
    ]
  },
  {
    'return_type' => 'apr_uuid_t *',
    'name' => 'mpxs_apr_uuid_parse',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'SV *',
        'name' => 'CLASS'
      },
      {
        'type' => 'char *',
        'name' => 'buf'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'mpxs_cleanup_run',
    'args' => [
      {
        'type' => 'void *',
        'name' => 'data'
      }
    ]
  },
  {
    'return_type' => 'apr_status_t',
    'name' => 'mpxs_modperl_bucket_read',
    'args' => [
      {
        'type' => 'PerlInterpreter *',
        'name' => 'my_perl'
      },
      {
        'type' => 'apr_bucket *',
        'name' => 'bucket'
      },
      {
        'type' => 'SV *',
        'name' => 'buffer'
      },
      {
        'type' => 'apr_read_type_e',
        'name' => 'block'
      }
    ]
  }
];


1;
