name:         mod_perl
version_from: lib/mod_perl.pm
installdirs:  site
distribution_type: module
no_index:
    directory:
        - Apache-Test
    package:
        - C::Preprocessed   
        - Apache
        - Apache::Constants
        - Apache::File
        - Apache::SIG
        - Apache::Server
        - Apache::Table
        - Apache::Util
