package Apache2::ConstantsTable;

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
# ! WARNING: generated by Apache2::ParseSource/0.02
# !          Tue Jun 12 09:42:50 2012
# !          do NOT edit, any changes will be lost !
# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

$Apache2::ConstantsTable = {
  'ModPerl' => {
    'common' => [
      'MODPERL_RC_EXIT'
    ]
  },
  'Apache2::Const' => {
    'types' => [
      'DIR_MAGIC_TYPE'
    ],
    'satisfy' => [
      'SATISFY_ALL',
      'SATISFY_ANY',
      'SATISFY_NOSPEC'
    ],
    'remotehost' => [
      'REMOTE_HOST',
      'REMOTE_NAME',
      'REMOTE_NOLOOKUP',
      'REMOTE_DOUBLE_REV'
    ],
    'platform' => [
      'LF',
      'CR',
      'CRLF',
      'CRLF_ASCII'
    ],
    'override' => [
      'OR_NONE',
      'OR_LIMIT',
      'OR_OPTIONS',
      'OR_FILEINFO',
      'OR_AUTHCFG',
      'OR_INDEXES',
      'OR_UNSET',
      'ACCESS_CONF',
      'RSRC_CONF',
      'EXEC_ON_READ',
      'OR_ALL'
    ],
    'options' => [
      'OPT_NONE',
      'OPT_INDEXES',
      'OPT_INCLUDES',
      'OPT_SYM_LINKS',
      'OPT_EXECCGI',
      'OPT_UNSET',
      'OPT_INCNOEXEC',
      'OPT_SYM_OWNER',
      'OPT_MULTI',
      'OPT_ALL',
      'OPT_INC_WITH_EXEC'
    ],
    'mpmq' => [
      'AP_MPMQ_NOT_SUPPORTED',
      'AP_MPMQ_STATIC',
      'AP_MPMQ_DYNAMIC',
      'AP_MPMQ_STARTING',
      'AP_MPMQ_RUNNING',
      'AP_MPMQ_STOPPING',
      'AP_MPMQ_MAX_DAEMON_USED',
      'AP_MPMQ_IS_THREADED',
      'AP_MPMQ_IS_FORKED',
      'AP_MPMQ_HARD_LIMIT_DAEMONS',
      'AP_MPMQ_HARD_LIMIT_THREADS',
      'AP_MPMQ_MAX_THREADS',
      'AP_MPMQ_MIN_SPARE_DAEMONS',
      'AP_MPMQ_MIN_SPARE_THREADS',
      'AP_MPMQ_MAX_SPARE_DAEMONS',
      'AP_MPMQ_MAX_SPARE_THREADS',
      'AP_MPMQ_MAX_REQUESTS_DAEMON',
      'AP_MPMQ_MAX_DAEMONS',
      'AP_MPMQ_MPM_STATE',
      'AP_MPMQ_IS_ASYNC'
    ],
    'methods' => [
      'M_GET',
      'M_PUT',
      'M_POST',
      'M_DELETE',
      'M_CONNECT',
      'M_OPTIONS',
      'M_TRACE',
      'M_PATCH',
      'M_PROPFIND',
      'M_PROPPATCH',
      'M_MKCOL',
      'M_COPY',
      'M_MOVE',
      'M_LOCK',
      'M_UNLOCK',
      'M_VERSION_CONTROL',
      'M_CHECKOUT',
      'M_UNCHECKOUT',
      'M_CHECKIN',
      'M_UPDATE',
      'M_LABEL',
      'M_REPORT',
      'M_MKWORKSPACE',
      'M_MKACTIVITY',
      'M_BASELINE_CONTROL',
      'M_MERGE',
      'M_INVALID',
      'METHODS'
    ],
    'log' => [
      'APLOG_EMERG',
      'APLOG_ALERT',
      'APLOG_CRIT',
      'APLOG_ERR',
      'APLOG_WARNING',
      'APLOG_NOTICE',
      'APLOG_INFO',
      'APLOG_DEBUG',
      'APLOG_LEVELMASK',
      'APLOG_TOCLIENT',
      'APLOG_STARTUP'
    ],
    'input_mode' => [
      'AP_MODE_READBYTES',
      'AP_MODE_GETLINE',
      'AP_MODE_EATCRLF',
      'AP_MODE_SPECULATIVE',
      'AP_MODE_EXHAUSTIVE',
      'AP_MODE_INIT'
    ],
    'http' => [
      'HTTP_CONTINUE',
      'HTTP_SWITCHING_PROTOCOLS',
      'HTTP_PROCESSING',
      'HTTP_OK',
      'HTTP_CREATED',
      'HTTP_ACCEPTED',
      'HTTP_NON_AUTHORITATIVE',
      'HTTP_NO_CONTENT',
      'HTTP_RESET_CONTENT',
      'HTTP_PARTIAL_CONTENT',
      'HTTP_MULTI_STATUS',
      'HTTP_MULTIPLE_CHOICES',
      'HTTP_MOVED_PERMANENTLY',
      'HTTP_MOVED_TEMPORARILY',
      'HTTP_SEE_OTHER',
      'HTTP_NOT_MODIFIED',
      'HTTP_USE_PROXY',
      'HTTP_TEMPORARY_REDIRECT',
      'HTTP_BAD_REQUEST',
      'HTTP_UNAUTHORIZED',
      'HTTP_PAYMENT_REQUIRED',
      'HTTP_FORBIDDEN',
      'HTTP_NOT_FOUND',
      'HTTP_METHOD_NOT_ALLOWED',
      'HTTP_NOT_ACCEPTABLE',
      'HTTP_PROXY_AUTHENTICATION_REQUIRED',
      'HTTP_REQUEST_TIME_OUT',
      'HTTP_CONFLICT',
      'HTTP_GONE',
      'HTTP_LENGTH_REQUIRED',
      'HTTP_PRECONDITION_FAILED',
      'HTTP_REQUEST_ENTITY_TOO_LARGE',
      'HTTP_REQUEST_URI_TOO_LARGE',
      'HTTP_UNSUPPORTED_MEDIA_TYPE',
      'HTTP_RANGE_NOT_SATISFIABLE',
      'HTTP_EXPECTATION_FAILED',
      'HTTP_UNPROCESSABLE_ENTITY',
      'HTTP_LOCKED',
      'HTTP_FAILED_DEPENDENCY',
      'HTTP_UPGRADE_REQUIRED',
      'HTTP_INTERNAL_SERVER_ERROR',
      'HTTP_NOT_IMPLEMENTED',
      'HTTP_BAD_GATEWAY',
      'HTTP_SERVICE_UNAVAILABLE',
      'HTTP_GATEWAY_TIME_OUT',
      'HTTP_VARIANT_ALSO_VARIES',
      'HTTP_INSUFFICIENT_STORAGE',
      'HTTP_NOT_EXTENDED'
    ],
    'filter_type' => [
      'AP_FTYPE_RESOURCE',
      'AP_FTYPE_CONTENT_SET',
      'AP_FTYPE_PROTOCOL',
      'AP_FTYPE_TRANSCODE',
      'AP_FTYPE_CONNECTION',
      'AP_FTYPE_NETWORK'
    ],
    'context' => [
      'NOT_IN_VIRTUALHOST',
      'NOT_IN_LIMIT',
      'NOT_IN_DIRECTORY',
      'NOT_IN_LOCATION',
      'NOT_IN_FILES',
      'NOT_IN_DIR_LOC_FILE',
      'GLOBAL_ONLY'
    ],
    'conn_keepalive' => [
      'AP_CONN_UNKNOWN',
      'AP_CONN_CLOSE',
      'AP_CONN_KEEPALIVE'
    ],
    'config' => [
      'DECLINE_CMD'
    ],
    'common' => [
      'DECLINED',
      'DONE',
      'OK',
      'NOT_FOUND',
      'FORBIDDEN',
      'AUTH_REQUIRED',
      'SERVER_ERROR',
      'REDIRECT'
    ],
    'cmd_how' => [
      'RAW_ARGS',
      'TAKE1',
      'TAKE2',
      'ITERATE',
      'ITERATE2',
      'FLAG',
      'NO_ARGS',
      'TAKE12',
      'TAKE3',
      'TAKE23',
      'TAKE123',
      'TAKE13',
      'TAKE_ARGV'
    ]
  },
  'APR::Const' => {
    'fprot' => [
      'APR_FPROT_USETID',
      'APR_FPROT_UREAD',
      'APR_FPROT_UWRITE',
      'APR_FPROT_UEXECUTE',
      'APR_FPROT_GSETID',
      'APR_FPROT_GREAD',
      'APR_FPROT_GWRITE',
      'APR_FPROT_GEXECUTE',
      'APR_FPROT_WSTICKY',
      'APR_FPROT_WREAD',
      'APR_FPROT_WWRITE',
      'APR_FPROT_WEXECUTE',
      'APR_FPROT_OS_DEFAULT'
    ],
    'fopen' => [
      'APR_FOPEN_READ',
      'APR_FOPEN_WRITE',
      'APR_FOPEN_CREATE',
      'APR_FOPEN_APPEND',
      'APR_FOPEN_TRUNCATE',
      'APR_FOPEN_BINARY',
      'APR_FOPEN_EXCL',
      'APR_FOPEN_BUFFERED',
      'APR_FOPEN_DELONCLOSE',
      'APR_FOPEN_XTHREAD',
      'APR_FOPEN_SHARELOCK',
      'APR_FOPEN_NOCLEANUP',
      'APR_FOPEN_SENDFILE_ENABLED',
      'APR_FOPEN_LARGEFILE'
    ],
    'filetype' => [
      'APR_FILETYPE_NOFILE',
      'APR_FILETYPE_REG',
      'APR_FILETYPE_DIR',
      'APR_FILETYPE_CHR',
      'APR_FILETYPE_BLK',
      'APR_FILETYPE_PIPE',
      'APR_FILETYPE_LNK',
      'APR_FILETYPE_SOCK',
      'APR_FILETYPE_UNKFILE'
    ]
  }
};


1;
